@startuml
'https://plantuml.com/component-diagram

package "Local" {
  [LocalMachine]
}

package "Map" {
  GRPC_MAP - [Map]
}

package "Mine" {
  GRPC_MINE - [MINE]
}

package "Mine2" {
  GRPC_MINE2 - [MINE2]
}


[LocalMachine] ---> [GRPC_MAP]
[GRPC_MINE] -> [GRPC_MAP]
[GRPC_MINE2] -> [GRPC_MAP]

legend
1. User creates node and send to Map.
2. Node connects to Map and send Ip, Updated Items, gets Node type, gets next nodes.
3. Node produces send item to next node if it can.
end legend


'cloud {
'}
'
'database "MySql" {
'}

@enduml