FROM golang:1.18-alpine as build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -o /app/run cmd/nodemap/main.go

FROM alpine

WORKDIR /app

COPY --from=build /app/nodemap/index.html  nodemap/index.html
COPY --from=build /app/run run

CMD ["/app/run"]