apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-dep
  labels:
    app: map-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map
  strategy:
    type:
      Recreate
  template:
    metadata:
      labels:
        app: map
    spec:
      containers:
        - name: map
          image: gcr.io/factorio2022/map:20220507130246
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "128Mi"
              cpu: "500m"
              ephemeral-storage: "100Mi"
          ports:
            - containerPort: 8081
              name: map-port
          volumeMounts:
            - name: volume1
              mountPath: /mnt/data
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: volumeclaim1
---
apiVersion: v1
kind: Service
metadata:
  name: map-ext
spec:
  selector:
    app: map
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: map-port
---
apiVersion: v1
kind: Service
metadata:
  name: map
spec:
  selector:
    app: map
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
