---
apiVersion: v1
kind: Pod
metadata:
  name: ${{ name }}
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: nginx:1.16
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
        ephemeral-storage: "100Mi"
      limits:
        memory: "128Mi"
        cpu: "500m"
        ephemeral-storage: "100Mi"
